version: "3"

services:
  db:
    image: postgres:13.1
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=devils_advocate

volumes:
  pgdata:
